-- ═══════════════════════════════════════════════════════════════════
-- Realm of the Mad God Exalt
-- ═══════════════════════════════════════════════════════════════════
--
-- Generated by: Steam Manifest Bot v4.0
-- Generated at: 2025-12-06T13:01:55.969Z
-- Steam App ID: 200210
-- Steam Store: https://store.steampowered.com/app/200210
-- SteamDB: https://steamdb.info/app/200210
--
-- ───────────────────────────────────────────────────────────────────
-- GAME INFORMATION
-- ───────────────────────────────────────────────────────────────────
-- Reviews: Metacritic 82% | Positive (194 reviews)
-- Base Depots: 2
-- DLC Count: 6
-- Valid DLC: 6
--
-- Data Sources: cmd, store
--
-- ═══════════════════════════════════════════════════════════════════
-- DEPOT MANIFEST DATA
-- ═══════════════════════════════════════════════════════════════════

-- Main Game
addappid(200210)

-- Base Game Depots (2)
-- ───────────────────────────────────────────────────────────────────
-- Depot 1: 200211 (public)
addappid(200211, 0, "e01ad1313cae36070b7cf01e260842cf00679ef43feef692bf98609b208b96cc")

-- Depot 2: 200212 (public)
addappid(200212, 0, "d3f02f52ec4c8ab99d771a29d8c66cf04eca4a8fd4444565c157f1e30b9adbfd")

-- DLC Depots (6)
-- ───────────────────────────────────────────────────────────────────
-- DLC 1: 294180 (App 294180)
addappid(294180, 0, "f6d62fda7a97bd60267884df3fa73bc1244632570e1f4f65b03cc59f78831b34")

-- DLC 2: 3306740 (App 3306740)
addappid(3306740, 0, "ddbdfd2f33b2d506f838c661de3d8fbbb75614e0f3119adb7bd54ff22da1e91d")

-- DLC 3: 3306750 (App 3306750)
addappid(3306750, 0, "8ce0bd7b08ec9b3118f78b777466a217bd98bcf3fd111ce60e5517863e1673f4")

-- DLC 4: 3306760 (App 3306760)
addappid(3306760, 0, "efa77d98e1fec891f0decfed51b89633610834a2be3f74771dfb286007c279bc")

-- DLC 5: 3306770 (App 3306770)
addappid(3306770, 0, "e3eb403aa11c6ac48bef9dd757c4bc5a60a63463b908a9026223b57b978e2bec")

-- DLC 6: 548380 (App 548380)
addappid(548380, 0, "2b9a42c155e7deec0edb28e52cc42eb6b27a3853a82d10398b3a23f912f73baf")

-- ═══════════════════════════════════════════════════════════════════
-- END OF MANIFEST
-- ═══════════════════════════════════════════════════════════════════
