-- Silent Hill f - Comprehensive Manifest
-- AppID: 2947440
-- Generated by: Steam Manifest Bot v6.0
-- 
-- Format: GreenLuma Reborn LUA
-- Status: TESTED - Compatible with SteamTool

-- MAIN GAME
addappid(2947440)

-- BASE GAME DEPOT
addappid(2947441, 1, "7c74a01f968aad2578848052bd545d93a2f8b9d97d498882b5230040447173e4")

-- DLC & BONUS CONTENT
addappid(3282160)
addtoken(3282160, "1723734955608826062")

addappid(3282170)
addtoken(3282170, "8745338579199605697")

addappid(3282180)
addtoken(3282180, "2435190140460799412")

addappid(3282190)
addtoken(3282190, "17422305961579312315")

addappid(3282720)
addtoken(3282720, "186020997252537705")

addappid(3282721, 1, "fd38a70c015f046a880fc4db0487fcccdf05e009b286cc4175abdddf61511342")

addappid(3516200)

-- END OF MANIFEST
