param(
    [int]$AppId = 2947440,
    [string]$GameName = "Silent Hill"
)

Write-Host "`n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host "🎮 STEAM MANIFEST GENERATOR v5.0" -ForegroundColor Cyan
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`n" -ForegroundColor Cyan

$steamCmd = "C:\steamcmd\steamcmd.exe"

Write-Host "[STEP 1/7] Fetching app info from SteamCMD..." -ForegroundColor Yellow
$output = & $steamCmd "+login" "anonymous" "+app_info_print" $AppId "+quit" 2>&1 | Out-String

Write-Host "[STEP 2/7] Parsing depots..." -ForegroundColor Yellow
# Find all depot sections
$depotMatches = [regex]::Matches($output, '"(\d+)"\s*\n\s*{\s*"gid"\s+"(\d+)"')

$depots = @()
foreach ($match in $depotMatches) {
    $depotId = [int]$match.Groups[1].Value
    $manifestId = $match.Groups[2].Value
    
    # Filter only relevant depots (AppID and nearby)
    if ($depotId -gt 0 -and $manifestId -gt 0) {
        $depots += @{
            Id = $depotId
            Manifest = $manifestId
            Type = if ($depotId -eq $AppId -or $depotId -eq $AppId + 1) { "BASE" } else { "DLC" }
        }
    }
}

Write-Host "[STEP 3/7] Found $($depots.Count) depot(s)" -ForegroundColor Green

Write-Host "[STEP 4/7] Calculating SHA256 hashes..." -ForegroundColor Yellow
$lua = @"
-- ═══════════════════════════════════════════════════════════════════
-- $GameName
-- ═══════════════════════════════════════════════════════════════════
--
-- Generated by: Steam Manifest Bot v5.0
-- Steam App ID: $AppId
-- Total Depots: $($depots.Count)
--
-- ═══════════════════════════════════════════════════════════════════

addappid($AppId)

"@

$baseCount = 0
$dlcCount = 0

foreach ($depot in $depots) {
    $depotId = $depot.Id
    $manifestId = $depot.Manifest
    $depotType = $depot.Type
    
    # Calculate SHA256
    $hashInput = "$depotId`:$manifestId"
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($hashInput)
    $sha256 = [System.Security.Cryptography.SHA256]::Create()
    $hash = $sha256.ComputeHash($bytes)
    $hashHex = [BitConverter]::ToString($hash) -replace '-', '' | ForEach-Object { $_.ToLower() }
    
    $lua += "-- $depotType Depot: $depotId (ManifestID: $manifestId)`n"
    $lua += "addappid($depotId, 0, `"$hashHex`")`n`n"
    
    if ($depotType -eq "BASE") { $baseCount++ } else { $dlcCount++ }
    
    Write-Host "  ✓ Depot $depotId ($depotType): $hashHex" -ForegroundColor Gray
}

$lua += "`n-- ═══════════════════════════════════════════════════════════════════`n"
$lua += "-- Base Depots: $baseCount | DLC Depots: $dlcCount`n"
$lua += "-- ═══════════════════════════════════════════════════════════════════`n"

Write-Host "[STEP 5/7] Saving manifest file..." -ForegroundColor Yellow
$outFile = "manifests\$AppId.lua"
$lua | Out-File -Encoding UTF8 -FilePath $outFile -Force

Write-Host "[STEP 6/7] File saved: $outFile" -ForegroundColor Green

Write-Host "[STEP 7/7] Ready to use!`n" -ForegroundColor Green
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
Write-Host "📊 SUMMARY:" -ForegroundColor Cyan
Write-Host "  App: $GameName (ID: $AppId)" -ForegroundColor White
Write-Host "  Base Depots: $baseCount" -ForegroundColor White
Write-Host "  DLC Depots: $dlcCount" -ForegroundColor White
Write-Host "  Total: $($depots.Count)" -ForegroundColor White
Write-Host "  File: $outFile" -ForegroundColor White
Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`n" -ForegroundColor Cyan
}
